title: Konstantin Kobs
description: My website showcasing all kinds of stuff, from music to scientific publications.
baseurl: ""
url: "http://konstantinkobs.de"

permalink: /:title

collections:
  - music

defaults:
  -
    scope:
      path: ""
    values:
      layout: "release"